export const recommendItems = [
  {
    id: 1,
    item: "Ring",
    image: require("../assets/recommend/men_gr1.jpg"),
    type: "gold",
    gender: "Male",
  },
  {
    id: 2,
    item: "Ring",
    image: require("../assets/recommend/men_gr2.jpg"),
    type: "gold",
    gender: "Male",
  },
  {
    id: 3,
    item: "Ring",
    image: require("../assets/recommend/men_gr3.jpg"),
    type: "gold",
    gender: "Male",
  },
  {
    id: 4,
    item: "Ring",
    image: require("../assets/recommend/men_gr4.jpg"),
    type: "gold",
    gender: "Male",
  },
  {
    id: 5,
    item: "Ring",
    image: require("../assets/recommend/female_gr1.jpg"),
    type: "gold",
    gender: "Female",
  },
  {
    id: 6,
    item: "Ring",
    image: require("../assets/recommend/female_gr2.jpg"),
    type: "gold",
    gender: "Female",
  },
  {
    id: 7,
    item: "Ring",
    image: require("../assets/recommend/female_gr3.jpg"),
    type: "gold",
    gender: "Female",
  },
  {
    id: 8,
    item: "Ring",
    image: require("../assets/recommend/female_gr4.jpg"),
    type: "gold",
    gender: "Female",
  },
  {
    id: 9,
    item: "Ring",
    image: require("../assets/recommend/mens_sr1.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 10,
    item: "Ring",
    image: require("../assets/recommend/mens_sr2.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 11,
    item: "Ring",
    image: require("../assets/recommend/mens_sr3.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 12,
    item: "Ring",
    image: require("../assets/recommend/mens_sr4.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 13,
    item: "Ring",
    image: require("../assets/recommend/female_sr1.jpg"),
    type: "Silver",
    gender: "Female",
  },
  {
    id: 14,
    item: "Ring",
    image: require("../assets/recommend/female_sr2.jpg"),
    type: "Silver",
    gender: "Female",
  },
  {
    id: 15,
    item: "Ring",
    image: require("../assets/recommend/female_sr3.jpg"),
    type: "Silver",
    gender: "Female",
  },
  {
    id: 16,
    item: "Ring",
    image: require("../assets/recommend/female_sr4.jpg"),
    type: "Silver",
    gender: "Female",
  },
  {
    id: 17,
    item: "Chain",
    image: require("../assets/recommend/female_gc1.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 18,
    item: "Chain",
    image: require("../assets/recommend/female_gc2.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 19,
    item: "Chain",
    image: require("../assets/recommend/female_gc3.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 20,
    item: "Chain",
    image: require("../assets/recommend/female_gc4.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 21,
    item: "Chain",
    image: require("../assets/recommend/mens_gc1.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 22,
    item: "Chain",
    image: require("../assets/recommend/mens_gc2.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 23,
    item: "Chain",
    image: require("../assets/recommend/mens_gc3.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 24,
    item: "Chain",
    image: require("../assets/recommend/mens_gc4.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 25,
    item: "Chain",
    image: require("../assets/recommend/mens_sc1.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 26,
    item: "Chain",
    image: require("../assets/recommend/mens_sc2.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 27,
    item: "Chain",
    image: require("../assets/recommend/mens_sc3.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 28,
    item: "Chain",
    image: require("../assets/recommend/mens_sc4.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 29,
    item: "Chain",
    image: require("../assets/recommend/female_sc1.jpg"),
    type: "Silver",
    gender: "Female",
  },
  {
    id: 30,
    item: "Chain",
    image: require("../assets/recommend/female_sc2.jpg"),
    type: "Silver",
    gender: "Female",
  },
  {
    id: 31,
    item: "Chain",
    image: require("../assets/recommend/female_sc3.jpg"),
    type: "Silver",
    gender: "Female",
  },
  {
    id: 32,
    item: "Chain",
    image: require("../assets/recommend/female_sc4.jpg"),
    type: "Silver",
    gender: "Female",
  },
  {
    id: 33,
    item: "Bracelet",
    image: require("../assets/recommend/mens_gb1.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 34,
    item: "Bracelet",
    image: require("../assets/recommend/mens_gb2.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 35,
    item: "Bracelet",
    image: require("../assets/recommend/mens_gb3.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 36,
    item: "Bracelet",
    image: require("../assets/recommend/mens_gb4.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 37,
    item: "Bracelet",
    image: require("../assets/recommend/mens_sb1.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 38,
    item: "Bracelet",
    image: require("../assets/recommend/mens_sb2.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 39,
    item: "Bracelet",
    image: require("../assets/recommend/mens_sb3.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 40,
    item: "Bracelet",
    image: require("../assets/recommend/mens_sb4.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 41,
    item: "Bracelet",
    image: require("../assets/recommend/female_gb1.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 42,
    item: "Bracelet",
    image: require("../assets/recommend/female_gb2.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 43,
    item: "Bracelet",
    image: require("../assets/recommend/female_gb3.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 44,
    item: "Bracelet",
    image: require("../assets/recommend/female_gb4.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 45,
    item: "Stud",
    image: require("../assets/recommend/mens_gs1.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 46,
    item: "Stud",
    image: require("../assets/recommend/mens_gs2.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 47,
    item: "Stud",
    image: require("../assets/recommend/mens_gs3.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 48,
    item: "Stud",
    image: require("../assets/recommend/mens_gs4.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 49,
    item: "Kada",
    image: require("../assets/recommend/mens_gk1.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 50,
    item: "Kada",
    image: require("../assets/recommend/mens_gk2.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 51,
    item: "Kada",
    image: require("../assets/recommend/mens_gk3.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 52,
    item: "Kada",
    image: require("../assets/recommend/mens_gk4.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 53,
    item: "Kada",
    image: require("../assets/recommend/mens_sk1.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 54,
    item: "Kada",
    image: require("../assets/recommend/mens_sk2.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 55,
    item: "Kada",
    image: require("../assets/recommend/mens_sk3.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 56,
    item: "Kada",
    image: require("../assets/recommend/mens_sk4.jpg"),
    type: "Silver",
    gender: "Male",
  },
  {
    id: 57,
    item: "Ring",
    image: require("../assets/recommend/female_dr1.jpg"),
    type: "Diamond",
    gender: "Female",
  },
  {
    id: 58,
    item: "Ring",
    image: require("../assets/recommend/female_dr2.jpg"),
    type: "Diamond",
    gender: "Female",
  },
  {
    id: 59,
    item: "Ring",
    image: require("../assets/recommend/female_dr3.jpg"),
    type: "Diamond",
    gender: "Female",
  },
  {
    id: 60,
    item: "Ring",
    image: require("../assets/recommend/female_dr4.jpg"),
    type: "Diamond",
    gender: "Female",
  },
  {
    id: 61,
    item: "Chain",
    image: require("../assets/recommend/female_dc1.jpg"),
    type: "Diamond",
    gender: "Female",
  },
  {
    id: 62,
    item: "Chain",
    image: require("../assets/recommend/female_dc2.jpg"),
    type: "Diamond",
    gender: "Female",
  },
  {
    id: 63,
    item: "Chain",
    image: require("../assets/recommend/female_dc3.jpg"),
    type: "Diamond",
    gender: "Female",
  },
  {
    id: 64,
    item: "Chain",
    image: require("../assets/recommend/female_dc4.jpg"),
    type: "Diamond",
    gender: "Female",
  },
  {
    id: 65,
    item: "Earings",
    image: require("../assets/recommend/female_ge1.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 66,
    item: "Earings",
    image: require("../assets/recommend/female_ge2.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 67,
    item: "Earings",
    image: require("../assets/recommend/female_ge3.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 68,
    item: "Earings",
    image: require("../assets/recommend/female_ge4.jpg"),
    type: "Gold",
    gender: "Female",
  },
  {
    id: 67,
    item: "Chain",
    image: require("../assets/recommend/mens_gc5.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 68,
    item: "Chain",
    image: require("../assets/recommend/mens_gc6.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 69,
    item: "Chain",
    image: require("../assets/recommend/mens_gc7.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 70,
    item: "Chain",
    image: require("../assets/recommend/mens_gc8.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 71,
    item: "Ring",
    image: require("../assets/recommend/men_gr5.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 72,
    item: "Ring",
    image: require("../assets/recommend/men_gr6.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 73,
    item: "Ring",
    image: require("../assets/recommend/men_gr7.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 74,
    item: "Ring",
    image: require("../assets/recommend/men_gr8.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 75,
    item: "Kada",
    image: require("../assets/recommend/mens_gk5.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 76,
    item: "Kada",
    image: require("../assets/recommend/mens_gk6.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 77,
    item: "Kada",
    image: require("../assets/recommend/mens_gk7.jpg"),
    type: "Gold",
    gender: "Male",
  },
  {
    id: 78,
    item: "Kada",
    image: require("../assets/recommend/mens_gk8.jpg"),
    type: "Gold",
    gender: "Male",
  },
];
